name:                bosu
version:             0.1.0.0
github:              "githubuser/bosu"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bosu#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- containers
- unordered-containers
- extra
- megaparsec >= 9.0.1
- text >= 1.2.4.0
- parser-combinators >= 1.2.1
- vector >= 0.12.1.2
- sdl2
- sdl2-mixer
- hgeometry
- hgeometry-combinatorial
- lens

library:
  source-dirs: src

executables:
  bosu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - bosu

tests:
  bosu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bosu
